server:
  port: 8707

spring:
  application:
    name: account-service

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8505/eureka/

spcloud:
  cassandra:
    port: 9042
    username: cassandra
    password: cassandra
    keyspace:
      name: springcloud
    contact:
      point: localhost